app = "dorm2-telegram-bot"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  LOG_LEVEL = "INFO"
  ENVIRONMENT = "production"

# Telegram bot не нужен HTTP сервер, убираем [http_service]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "bot_data"
  destination = "/app/data" 